### ISSUE TITLE
New Google recaptcha API not supported

### ISSUE THREAD

**Issue by Failproofshark** [madnificent/cl-recaptcha#1]
It seems that the API referenced and used in the current branch of code is out of date. Google has recently updated the API providing new features and empahsizing the use of the Javascript enabled version of the recaptcha facility. 

I have made a pull request with code that brings the library up to speed with the new API. I tested it out with a small test Clack application I made, which is not included. If you want the test Clack application I will happily provide it

**Comment by madnificent** [comment]
Pull request merged, library version upgraded.  Thank you for your input.
